        
aml_nftl_dev-objs =
aml_nftl_dev-objs += block/aml_nftl_block.o
aml_nftl_dev-objs += block/aml_nftl_init.o
aml_nftl_dev-objs += block/aml_nftl_hw_interface.o

aml_nftl_dev-objs += ../../../../../../../../../hardware/amlogic/nand/aml_nftl_new/nftl/aml_nftl_core_20131226.z

obj-$(CONFIG_AML_NFTL_NEW)	+= aml_nftl_dev.o
